package guru.sfg.beer.order.service.domain;

/**
 * Created by jt on 11/29/19.
 */
public enum BeerOrderEventEnum {
    VALIDATE_ORDER, CANCEL_ORDER, VALIDATION_PASSED, VALIDATION_FAILED,
    ALLOCATE_ORDER, ALLOCATION_SUCCESS, ALLOCATED, ALLOCATION_NO_INVENTORY, ALLOCATION_FAILED,
    START_DELIVERY, DELIVERED, DELIVERY_FAILED
}
